vim.cmd("colorscheme nightfox")
local transparent = require("transparent")
transparent.setup({
	-- table: default groups
	groups = {
		"Normal",
		"NormalNC",
		"Comment",
		"Constant",
		"Special",
		"Identifier",
		"Statement",
		"PreProc",
		"Type",
		"Underlined",
		"Todo",
		"String",
		"Function",
		"Conditional",
		"Repeat",
		"Operator",
		"Structure",
		"LineNr",
		"NonText",
		"SignColumn",
		"CursorLine",
		"CursorLineNr",
		"StatusLine",
		"StatusLineNC",
		"EndOfBuffer",
		"TSContextLine",
		"NeorgCodeBlock",
		"NeorgCodeBlockNormal",
		"TSPunctDelimiter",
		"@neorg.tags.ranged_verbatim.code_block",
		"TabLine",
		"TabLineSel",
		"TabLineFill",
		"WinBar",
		"WinBarNC",
		"FzfLuaNormal",
		"FzfLuaBorder",
		"FzfLuaPromptNormal",
		"FzfLuaPromptBorder",
		"FzfLuaNormal",
		"FzfLuaBorder",
		"FzfLuaPromptNormal ",
		"FzfLuaPromptBorder ",
		"FzfLuaPreviewNormal",
		"FzfLuaPreviewBorder",
		"CursorLine",
		"CursorLineNC",
		"NormalFloat",
		"FzfLuaNormal",
		"FzfLuaBorder",
		"FzfLuaPromptNormal ",
		"FzfLuaPromptBorder ",
		"FzfLuaPreviewNormal",
		"FzfLuaPreviewBorder",
		"VertSplit",
	},
	-- table: additional groups that should be cleared
	extra_groups = {},
	-- table: groups you don't want to clear
	exclude_groups = {},
	-- function: code to be executed after highlight groups are cleared
	-- Also the user event "TransparentClear" will be triggered
	on_clear = function() end,
})
